### PR TITLE
update ts-jest

### LINKED ISSUE #318: An in-range update of ts-jest is breaking the build 🚨
## The devDependency [ts-jest](https://github.com/kulshekhar/ts-jest) was updated from `24.0.0` to `24.0.1`.

🚨 [View failing branch](https://github.com/intuit/auto/compare/master...intuit:greenkeeper%2Fts-jest-24.0.1).

This version is **covered** by your **current version range** and after updating it in your project **the build failed**.

ts-jest is a devDependency of this project. It **might not break your production code or affect downstream projects**, but probably breaks your build or test tools, which may **prevent deploying or publishing**.

<details>
<summary>Status Details</summary>

- ❌ **ci/circleci: install:** Your tests failed on CircleCI ([Details](https://circleci.com/gh/intuit/auto/3759?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)).
</details>

---

<details>
<summary>Commits</summary>
<p>The new version differs by 23 commits.</p>
<ul>
<li><a href="https://urls.greenkeeper.io/kulshekhar/ts-jest/commit/b43b3c10233801b8dcd15e6fb5b16c508beb0a2e"><code>b43b3c1</code></a> <code>chore(release): 24.0.1</code></li>
<li><a href="https://urls.greenkeeper.io/kulshekhar/ts-jest/commit/2d91a3782432c8485aec90d2878a1149f6d85bcf"><code>2d91a37</code></a> <code>chore: update package-lock</code></li>
<li><a href="https://urls.greenkeeper.io/kulshekhar/ts-jest/commit/485d3f798d1e4a1437851e67529cae2920777225"><code>485d3f7</code></a> <code>build(deps): bump semver from 5.6.0 to 5.7.0 (#1043)</code></li>
<li><a href="https://urls.greenkeeper.io/kulshekhar/ts-jest/commit/2bd2534178854ccbc8a01c0dbd95f7c6e9e49a47"><code>2bd2534</code></a> <code>build(deps-dev): bump @types/node from 10.14.3 to 10.14.4 (#1041)</code></li>
<li><a href="https://urls.greenkeeper.io/kulshekhar/ts-jest/commit/bdba560c82cf707ab05f9fa69af773a91e3cce15"><code>bdba560</code></a> <code>build(deps-dev): bump @types/node from 10.14.2 to 10.14.3 (#1038)</code></li>
<li><a href="https://urls.greenkeeper.io/kulshekhar/ts-jest/commit/08766bf401323a288babcbe206ce1e8d7e2ed4f0"><code>08766bf</code></a> <code>build(deps-dev): bump @types/node from 10.14.1 to 10.14.2 (#1036)</code></li>
<li><a href="https://urls.greenkeeper.io/kulshekhar/ts-jest/commit/5f92fd29446d6ed2b71102cc27e03930fd79984f"><code>5f92fd2</code></a> <code>build(deps-dev): bump js-yaml from 3.12.2 to 3.13.0 (#1034)</code></li>
<li><a href="https://urls.greenkeeper.io/kulshekhar/ts-jest/commit/a9c79e9afc1151d42a9a59e62c9b90f09ca603cf"><code>a9c79e9</code></a> <code>build(deps-dev): bump @types/yargs from 12.0.9 to 12.0.10 (#1032)</code></li>
<li><a href="https://urls.greenkeeper.io/kulshekhar/ts-jest/commit/245ab29560ef60db8ae6e2e660cf9ab221566616"><code>245ab29</code></a> <code>build(deps-dev): bump eslint from 5.15.2 to 5.15.3 (#1031)</code></li>
<li><a href="https://urls.greenkeeper.io/kulshekhar/ts-jest/commit/4e72e596e9d3fc4125a02961ea19793f6f0d7df8"><code>4e72e59</code></a> <code>build(deps-dev): bump eslint from 5.15.1 to 5.15.2 (#1030)</code></li>
<li><a href="https://urls.greenkeeper.io/kulshekhar/ts-jest/commit/fb7dd558fb06a822a4911f5c00b1853204a971cf"><code>fb7dd55</code></a> <code>feat(config): specify package.json location (#823) (#1013)</code></li>
<li><a href="https://urls.greenkeeper.io/kulshekhar/ts-jest/commit/279edcd759602b5246c6921496801ac62af7d688"><code>279edcd</code></a> <code>build(deps-dev): bump tslint from 5.13.1 to 5.14.0 (#1028)</code></li>
<li><a href="https://urls.greenkeeper.io/kulshekhar/ts-jest/commit/8b932289c09322d7d8644bb5270aa75782673ac1"><code>8b93228</code></a> <code>build(deps-dev): bump @types/node from 10.12.30 to 10.14.1 (#1027)</code></li>
<li><a href="https://urls.greenkeeper.io/kulshekhar/ts-jest/commit/b825c7fc263f57ac76655d997be23ef667d61f00"><code>b825c7f</code></a> <code>build(deps-dev): bump @types/lodash.memoize from 4.1.4 to 4.1.6 (#1014)</code></li>
<li><a href="https://urls.greenkeeper.io/kulshekhar/ts-jest/commit/6f0ab80277066cfb0447371c7c95709ece05f37f"><code>6f0ab80</code></a> <code>build(deps-dev): bump @types/lodash.merge from 4.6.5 to 4.6.6 (#1015)</code></li>
</ul>
<p>There are 23 commits in total.</p>
<p>See the <a href="https://urls.greenkeeper.io/kulshekhar/ts-jest/compare/1ac501ac52986c0f143900c2a441f472666f4991...b43b3c10233801b8dcd15e6fb5b16c508beb0a2e">full diff</a></p>
</details>

<details>
<summary>FAQ and help</summary>

There is a collection of [frequently asked questions](https://greenkeeper.io/faq.html). If those don’t help, you can always [ask the humans behind Greenkeeper](https://github.com/greenkeeperio/greenkeeper/issues/new).
</details>

---

Your [Greenkeeper](https://greenkeeper.io) Bot :palm_tree:

### PR DESCRIPTION
**Pull request by hipstersmoothie**
closes #318

### CODE REVIEW

**Comment by adierkens** [comment]
:rocket: PR was released in v4.8.16 :rocket:

**Comment by hipstersmoothie** [comment]
:rocket: PR was released in v4.8.16 :rocket:

**Comment by hipstersmoothie** [comment]
:rocket: PR was released in v4.8.16 :rocket:

**Comment by hipstersmoothie** [comment]
:rocket: PR was released in v4.8.16 :rocket:

**Pull request merged**
