### PR TITLE
Add clarity to a few of the docs

### PR DESCRIPTION
**Pull request by zephraph**
# What Changed

Doc updates

# Why

House keeping

---

I think while I'm here we could potentially add some more clarification around behavior. Here's general questions I had while reading through the plugin docs...

1. If you specify a plugin, does that clear out the default plugin? i.e. if I want to use `release` do I have to add `npm` as well so I don't lose that?
2. For the [npm package plugin](https://intuit.github.io/auto/pages/plugins.html#2.-npm-package), is it required that said plugin be installed as a dependency of the project? That same question probably extends to extensions. Pretty sure that _do_ have to be dependencies.

### CODE REVIEW

**Comment by hipstersmoothie** [comment]
1. yes
2. all current `official` plugins are included with `auto` and aren't distributed individually. in the future we will probably go with a monorepo

**Comment by zephraph** [comment]
Oh, right. The built-in plugins are provided. These docs seem to imply that external plugins can be supplied arbitrarily as the name of npm packages. Guess the open question there was... do those plugins (none of which likely exist at the moment) need to be a dependency of the project. Fairly certain the answer is yes. I just want to clarify before updaing the docs.

**Comment by hipstersmoothie** [comment]
Oh yeah they would need to be dependancies. All we do is try to require the plugin in a few different ways https://github.com/intuit/auto/blob/master/src/utils/load-plugins.ts#L35

**Comment by zephraph** [comment]
Okay, check those out. Hopefully there's no typos, heh.

**Comment by adierkens** [comment]
:rocket: PR was released in v4.4.1 :rocket:

**Pull request merged**
