### PR TITLE
Crates (Rust language) plugin

### PR DESCRIPTION
**Pull request by Celeo**
# What Changed

Add a Rust plugin to publish Rust crates to crates.io.

# Why

Because there wasn't such a plugin.

Todo:

- [x] Add tests
- [x] Add docs
- [x] Add yourself to contributors (run `yarn contributors:add`)
- [x] Manually test on a crate

Published PR with canary version: `7.8.1-canary.587.7827.0`

### CODE REVIEW

**Comment by Celeo** [comment]
As noted in the description; I still have some manual testing to do.

**Comment by Celeo** [comment]
What _is_ the suggested flow for locally testing an in-dev plugin? I can add a simple node project over my rust project, install `auto`, and "install" my plugin with a link - should that do it?

**Comment by hipstersmoothie** [comment]
Options for testing locally:

1. If the build work you will get a canary version of auto and your plugin. You could install this with npm globally and you should be able to use it from the terminal
2. You could try to run the [`bundle`](https://github.com/intuit/auto/blob/master/packages/cli/package.json#L40) command on the CLI (after everything is built) to get a platform specific executable
3. You could wrap your rust project like you said

> I'm having trouble doing anything from the cli; I'm getting bad credentials errors but that's using a PAT with all scopes enabled.

This is odd. I'm not sure what might be going wrong. You can run with `-v` or `-w` to get verbose or very verbose output to try and help debug. If you want to stop by my desk we could debug also!

**Comment by Celeo** [comment]
I figured out my GH API issues; moving forward.

**Comment by Celeo** [comment]
Got it working!

https://i.imgur.com/oRBrfgA.png
https://i.imgur.com/WEKjnH7.png

**Comment by Celeo** [comment]
Should this plugin be called 'rust' or 'cargo' (the package manger) or 'crates' (the [Rust version of npmjs.org](https://crates.io/))?

**Comment by hipstersmoothie** [comment]
> Should this plugin be called 'rust' or 'cargo' (the package manger) or 'crates' (the Rust version of npmjs.org)?

the other plugins are the package manger names so we should stick with that.

**Comment by hipstersmoothie** [comment]
a few things need to be updated for docs:

1. add a link in the root readme
2. add the readme to the index of the docs https://github.com/intuit/auto/blob/master/docs/index.md

**Comment by Celeo** [comment]
Updated, thanks.

I'm unsure why the build is failing: it works on my machine & the CI job has an odd error code - 137 (getting cancelled?).

**Comment by adierkens** [comment]
:rocket: PR was released in v7.9.0 :rocket:

**Pull request merged**
