### PR TITLE
Updating all-contributors-cli dependency

### PR DESCRIPTION
**Pull request by jdalrymple**
# What Changed

Updated the all-contributors-cli dependency

## Why

To support new configuration within the cli 

Todo:

- [ ] Add tests
- [ ] Add docs

## Change Type

Indicate the type of change your pull request is:

- [ ] `documentation`
- [ ] `patch`
- [x] `minor`
- [ ] `major`

### CODE REVIEW

**Comment by hipstersmoothie** [comment]
@jdalrymple doesn't look like the lock file is fully updated

**Comment by jdalrymple** [comment]
Oh darn! Will do. Which version of yarn? I want to make sure when i do the update it doesnt refresh all of the yarn files

**Comment by hipstersmoothie** [comment]
we're on v1

**Comment by jdalrymple** [comment]
Looking at the failed tasks, should i be addressing the typing errors in other files?

**Comment by hipstersmoothie** [comment]
Looks like there is only lint failures now. Once that's good I can merge

**Comment by jdalrymple** [comment]
> Looks like there is only lint failures now. Once that's good I can merge

Yes, but in a file that wasnt changed...?

>/home/runner/work/auto/auto/packages/core/src/release.ts
Error:   1:33  error  Unable to resolve path to module 'type-fest'  import/no-unresolved

**Comment by jdalrymple** [comment]
Looking into it! Might be related to yarn

**Comment by hipstersmoothie** [comment]
I'll pull this today and figure it out!

**Comment by jdalrymple** [comment]
Using this lib: https://github.com/import-js/eslint-import-resolver-typescript, might help, though my tests with it didnt solve the issue

**Pull request closed without merging**
