### PR TITLE
update command line args

### LINKED ISSUE #319: An in-range update of command-line-args is breaking the build 🚨
## The dependency [command-line-args](https://github.com/75lb/command-line-args) was updated from `5.1.0` to `5.1.1`.

🚨 [View failing branch](https://github.com/intuit/auto/compare/master...intuit:greenkeeper%2Fcommand-line-args-5.1.1).

This version is **covered** by your **current version range** and after updating it in your project **the build failed**.

command-line-args is a direct dependency of this project, and **it is very likely causing it to break**. If other packages depend on yours, this update is probably also breaking those in turn.

<details>
<summary>Status Details</summary>

- ❌ **ci/circleci: install:** Your tests failed on CircleCI ([Details](https://circleci.com/gh/intuit/auto/3761?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)).
</details>

---

<details>
<summary>Commits</summary>
<p>The new version differs by 7 commits.</p>
<ul>
<li><a href="https://urls.greenkeeper.io/75lb/command-line-args/commit/b07cb35ed0d1f3632230cb658e1e8c5a238e38fa"><code>b07cb35</code></a> <code>5.1.1</code></li>
<li><a href="https://urls.greenkeeper.io/75lb/command-line-args/commit/e28c9b0c69bcd9a58d67237705364970249f9626"><code>e28c9b0</code></a> <code>use .indexOf instead of .includes for node v4 compatibility</code></li>
<li><a href="https://urls.greenkeeper.io/75lb/command-line-args/commit/b9860f4292988922780e883a4c8b70b0f7e61b3b"><code>b9860f4</code></a> <code>add tests and support for '--exec='</code></li>
<li><a href="https://urls.greenkeeper.io/75lb/command-line-args/commit/62cca9867cd68e56d1284a18307cb021f6612e28"><code>62cca98</code></a> <code>Merge branch 'parse-correctly-when-eval-option' of <a href="https://urls.greenkeeper.io/zawataki/command-line-args">https://github.com/zawataki/command-line-args</a> into zawataki-parse-correctly-when-eval-option</code></li>
<li><a href="https://urls.greenkeeper.io/75lb/command-line-args/commit/f87d7bac681c81c62c608b8a549c931514d09c6d"><code>f87d7ba</code></a> <code>Merge pull request #100 from zawataki/master</code></li>
<li><a href="https://urls.greenkeeper.io/75lb/command-line-args/commit/3da987f9cc25fe2397fbe4a9cf091595d50cb585"><code>3da987f</code></a> <code>Parse correctly when Node runs with --eval or -e</code></li>
<li><a href="https://urls.greenkeeper.io/75lb/command-line-args/commit/e88e500ff6d98d21cd693a363f46e72c3b087458"><code>e88e500</code></a> <code>Make git ignore node_modules directory</code></li>
</ul>
<p>See the <a href="https://urls.greenkeeper.io/75lb/command-line-args/compare/6ef337e51842e5b3e05adb007c140ee90ee2ba68...b07cb35ed0d1f3632230cb658e1e8c5a238e38fa">full diff</a></p>
</details>

<details>
<summary>FAQ and help</summary>

There is a collection of [frequently asked questions](https://greenkeeper.io/faq.html). If those don’t help, you can always [ask the humans behind Greenkeeper](https://github.com/greenkeeperio/greenkeeper/issues/new).
</details>

---

Your [Greenkeeper](https://greenkeeper.io) Bot :palm_tree:

### PR DESCRIPTION
**Pull request by hipstersmoothie**
closes #319

### CODE REVIEW

**Comment by adierkens** [comment]
:rocket: PR was released in v4.8.16 :rocket:

**Comment by hipstersmoothie** [comment]
:rocket: PR was released in v4.8.16 :rocket:

**Comment by hipstersmoothie** [comment]
:rocket: PR was released in v4.8.16 :rocket:

**Comment by hipstersmoothie** [comment]
:rocket: PR was released in v4.8.16 :rocket:

**Pull request merged**
