### PR TITLE
update node types

### LINKED ISSUE #317: An in-range update of @types/node is breaking the build 🚨
## The devDependency [@types/node](https://github.com/DefinitelyTyped/DefinitelyTyped) was updated from `11.12.1` to `11.12.2`.

🚨 [View failing branch](https://github.com/intuit/auto/compare/master...intuit:greenkeeper%2F%40types%2Fnode-11.12.2).

This version is **covered** by your **current version range** and after updating it in your project **the build failed**.

@types/node is a devDependency of this project. It **might not break your production code or affect downstream projects**, but probably breaks your build or test tools, which may **prevent deploying or publishing**.

<details>
<summary>Status Details</summary>

- ❌ **ci/circleci: install:** Your tests failed on CircleCI ([Details](https://circleci.com/gh/intuit/auto/3757?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)).
</details>

---

<details>
<summary>FAQ and help</summary>

There is a collection of [frequently asked questions](https://greenkeeper.io/faq.html). If those don’t help, you can always [ask the humans behind Greenkeeper](https://github.com/greenkeeperio/greenkeeper/issues/new).
</details>

---

Your [Greenkeeper](https://greenkeeper.io) Bot :palm_tree:

### PR DESCRIPTION
**Pull request by hipstersmoothie**
closes #317

### CODE REVIEW

**Comment by adierkens** [comment]
:rocket: PR was released in v4.8.16 :rocket:

**Comment by hipstersmoothie** [comment]
:rocket: PR was released in v4.8.16 :rocket:

**Comment by hipstersmoothie** [comment]
:rocket: PR was released in v4.8.16 :rocket:

**Comment by hipstersmoothie** [comment]
:rocket: PR was released in v4.8.16 :rocket:

**Comment by hipstersmoothie** [comment]
:rocket: PR was released in v4.8.16 :rocket:

**Pull request merged**
