### PR TITLE
Maven plugin support for configurable SNAPSHOT branch

### PR DESCRIPTION
**Pull request by rbellamy**
# Why

Currently, the Maven plugin has an undocumented requirement for a "dev-snapshot" branch for committing the next SNAPSHOT version after release. Also, `MAVEN_USERNAME`, `MAVEN_PASSWORD`, and `MAVEN_SETTINGS` are undocumented environment variables.

# What Changed

1. Add a new environment variable `MAVEN_SNAPSHOT_BRANCH` that can be used to configure the SNAPSHOT branch.
2. Document all environment variables used by this plugin directly. *NOTE: environment variables used in a `pom.xml` or `settings.xml` or other Maven configuration files are NOT documented here.*

Todo:

- [x] Add tests
- [ ] Add docs

<details>
  <summary>📦 Published PR as canary version: <code>under canary scope @auto-canary@9.34.2-canary.1241.15885.0</code></summary>
  <br />
  
  :sparkles: Test out this PR locally via:
  
  ```sh
  npm install @auto-canary/bot-list@9.34.2-canary.1241.15885.0
  npm install @auto-canary/auto@9.34.2-canary.1241.15885.0
  npm install @auto-canary/core@9.34.2-canary.1241.15885.0
  npm install @auto-canary/all-contributors@9.34.2-canary.1241.15885.0
  npm install @auto-canary/brew@9.34.2-canary.1241.15885.0
  npm install @auto-canary/chrome@9.34.2-canary.1241.15885.0
  npm install @auto-canary/cocoapods@9.34.2-canary.1241.15885.0
  npm install @auto-canary/conventional-commits@9.34.2-canary.1241.15885.0
  npm install @auto-canary/crates@9.34.2-canary.1241.15885.0
  npm install @auto-canary/exec@9.34.2-canary.1241.15885.0
  npm install @auto-canary/first-time-contributor@9.34.2-canary.1241.15885.0
  npm install @auto-canary/gh-pages@9.34.2-canary.1241.15885.0
  npm install @auto-canary/git-tag@9.34.2-canary.1241.15885.0
  npm install @auto-canary/gradle@9.34.2-canary.1241.15885.0
  npm install @auto-canary/jira@9.34.2-canary.1241.15885.0
  npm install @auto-canary/maven@9.34.2-canary.1241.15885.0
  npm install @auto-canary/npm@9.34.2-canary.1241.15885.0
  npm install @auto-canary/omit-commits@9.34.2-canary.1241.15885.0
  npm install @auto-canary/omit-release-notes@9.34.2-canary.1241.15885.0
  npm install @auto-canary/released@9.34.2-canary.1241.15885.0
  npm install @auto-canary/s3@9.34.2-canary.1241.15885.0
  npm install @auto-canary/slack@9.34.2-canary.1241.15885.0
  npm install @auto-canary/twitter@9.34.2-canary.1241.15885.0
  npm install @auto-canary/upload-assets@9.34.2-canary.1241.15885.0
  # or 
  yarn add @auto-canary/bot-list@9.34.2-canary.1241.15885.0
  yarn add @auto-canary/auto@9.34.2-canary.1241.15885.0
  yarn add @auto-canary/core@9.34.2-canary.1241.15885.0
  yarn add @auto-canary/all-contributors@9.34.2-canary.1241.15885.0
  yarn add @auto-canary/brew@9.34.2-canary.1241.15885.0
  yarn add @auto-canary/chrome@9.34.2-canary.1241.15885.0
  yarn add @auto-canary/cocoapods@9.34.2-canary.1241.15885.0
  yarn add @auto-canary/conventional-commits@9.34.2-canary.1241.15885.0
  yarn add @auto-canary/crates@9.34.2-canary.1241.15885.0
  yarn add @auto-canary/exec@9.34.2-canary.1241.15885.0
  yarn add @auto-canary/first-time-contributor@9.34.2-canary.1241.15885.0
  yarn add @auto-canary/gh-pages@9.34.2-canary.1241.15885.0
  yarn add @auto-canary/git-tag@9.34.2-canary.1241.15885.0
  yarn add @auto-canary/gradle@9.34.2-canary.1241.15885.0
  yarn add @auto-canary/jira@9.34.2-canary.1241.15885.0
  yarn add @auto-canary/maven@9.34.2-canary.1241.15885.0
  yarn add @auto-canary/npm@9.34.2-canary.1241.15885.0
  yarn add @auto-canary/omit-commits@9.34.2-canary.1241.15885.0
  yarn add @auto-canary/omit-release-notes@9.34.2-canary.1241.15885.0
  yarn add @auto-canary/released@9.34.2-canary.1241.15885.0
  yarn add @auto-canary/s3@9.34.2-canary.1241.15885.0
  yarn add @auto-canary/slack@9.34.2-canary.1241.15885.0
  yarn add @auto-canary/twitter@9.34.2-canary.1241.15885.0
  yarn add @auto-canary/upload-assets@9.34.2-canary.1241.15885.0
  ```
</details>

### CODE REVIEW

**Comment by rbellamy** [comment]
Gah, sorry, forgot to pull in upstream master before building this PR.

**Comment by hipstersmoothie** [comment]
In the future this plugin should probably move to look more like the `gradle` plugin but I'm no maven whiz. 

the gradle plugin:

- enables snapshot versioning if you want it
- doesn't do any of this `git` hackery

If you consider yourself a maven whiz I'm all for PRs that make this plugin work better. Thanks for the docs!

**Comment by adierkens** [comment]
:rocket: PR was released in [`v9.35.0`](https://github.com/intuit/auto/releases/tag/v9.35.0) :rocket:

**Comment by rbellamy** [comment]
@hipstersmoothie I'll look at the gradle plugin for sure. We're exclusively a maven shop, so that's where I'll need the magic. For the record, I probably wouldn't have gone with the maven release plugin for wiring it up to auto, mostly because a good portion of the work the plugin does is messy and already addressed via the tooling available in auto.

That said, there are significant exceptions - not least of which is the management of SNAPSHOTs and updating versions in the `pom.xml` files.

Although, I just realized something - this plugin doesn't address multi-module projects!

**Comment by rbellamy** [comment]
Also, sending another PR your way - I missed one of the sections that's using the "dev-snapshot" branch.

**Comment by hipstersmoothie** [comment]
Yeah I didn't really know how to go about it without the maven release plugin. I would have preferred to use pure maven command (like the npm plugin does)

> Although, I just realized something - this plugin doesn't address multi-module projects!

This would be an awesome addition to `auto`!

---

If we decide that we need a major to make the maven plugin amazing I'm down!

**Comment by rbellamy** [comment]
>This would be an awesome addition to auto!

I agree, and it's a must-have for me, so a PR is pending.

**Pull request merged**
